### ISSUE TITLE
[Bug] RuntimeError: "index_reduce_func_cuda_exclude_input_init" not implemented for 'Long'

### ISSUE THREAD

**Issue by xinyue-sun** [yuyi1005/mmrotate#3]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

conda create --name openmmlab python=3.7 -y
 conda activate openmmlab
 //安装pytorch #cuda11.6
 conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=11.6 -c pytorch -c conda-forge
 //安装mmrotate
 pip install -U openmim
 mim install mmengine
 mim install mmcv==2.0.0rc4   #要求mmcv>=2.0.0rc4, <2.1.0.
 mim install mmdet==3.1.0
 （Successfully installed mmdet-3.1.0）
 pip install -r requirements.txt
 pip install -r requirements/build.txt
 pip install -v -e .

### Reproduces the problem - code sample

if self.agnostic_cls:
    pair_labels = torch.empty(
        bid.shape,                  #[77]  torch.float32
        dtype=target_labels.dtype,  #torch.int64
        device=bid.device).index_reduce_(
            0,
            idx,
            target_labels,
            'mean',
            include_self=False)[bmsk].view(-1, 2)[:, 0]

### Reproduces the problem - command or script

export CUDA_VISIBLE_DEVICES=0,1
# DOTA
WORK_DIR='xxx/work_dir/point2rbox-yolof-dota/'
tools/dist_train.sh configs/point2rbox/point2rbox-yolof-dota.py 2 \
                    --work-dir ${WORK_DIR} 

### Reproduces the problem - error message

/data/lxy/point2rbox-mmrotate-dev-1.x/mmrotate/models/dense_heads/point2rbox_yolof_head.py:420: UserWarning: index_reduce() is in beta and the API may change at any time. (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352463056/work/aten/src/ATen/native/cuda/Indexing.cu:880.)
  pair_bid_targets = torch.empty_like(bid).index_reduce_(
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 121, in main
    runner.train()
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 98, in run
    self.run_epoch()
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 115, in run_epoch
    self.run_iter(idx, data_batch)
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 131, in run_iter
    outputs = self.runner.model.train_step(
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
    losses = self._run_forward(data, mode='loss')
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    results = self(**data, mode=mode)
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/data/lxy/point2rbox-mmrotate-dev-1.x/mmrotate/models/detectors/point2rbox_yolof.py", line 344, in loss
    losses = self.bbox_head.loss(feat, batch_data_samples_all)
  File "/data/lxy/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 123, in loss
    losses = self.loss_by_feat(*loss_inputs)
  File "/data/lxy/point2rbox-mmrotate-dev-1.x/mmrotate/models/dense_heads/point2rbox_yolof_head.py", line 512, in loss_by_feat
    pair_labels = torch.empty(
RuntimeError: "index_reduce_func_cuda_exclude_input_init" not implemented for 'Long'

### Additional information

1、The problem arises when I'm working on https://github.com/yuyi1005/point2rbox-mmrotate/tree/dev-1.x
2、It maybe the difference of pytorch version that caused this error I think. Could I know the version of pytorch did you use? Thank you!

**Comment by yuyi1005** [comment]
Please use PyTorch 1.13 or higher
